# Generated by Django 5.0.4 on 2024-10-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
