# Generated by Django 5.0.4 on 2024-10-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rut',
            field=models.CharField(max_length=12, null=True, verbose_name='Rut'),
        ),
    ]
