# Generated by Django 5.0.4 on 2024-08-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('status', models.CharField(choices=[('PC', 'Pendiente Confirmación'), ('CF', 'Confirmado'), ('EP', 'En preparación'), ('EN', 'Entregado'), ('CN', 'Cancelado')], default='PC', max_length=2, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Precio unitario')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'detalle solicitud',
                'verbose_name_plural': 'detalle solicitudes',
            },
        ),
    ]
