# Generated by Django 5.0.4 on 2024-05-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cameras',
            field=models.IntegerField(default=0, verbose_name='Cámaras'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='channels',
            field=models.IntegerField(default=0, verbose_name='Canales'),
            preserve_default=False,
        ),
    ]
