# Generated by Django 5.0.4 on 2024-06-03 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_cameras_product_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NOMBRE')),
                ('last_name', models.CharField(max_length=50, verbose_name='APELLIDO')),
                ('birthday', models.DateField(verbose_name='FECHA DE NACIMIENTO')),
                ('phone_number', models.IntegerField(unique=True, verbose_name='TELÉFONO')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna', verbose_name='COMUNA')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['last_name'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
