# Generated by Django 5.0.4 on 2024-10-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_fees_order_updated_at_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
