# Generated by Django 5.0.4 on 2024-06-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comuna_solicitud_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['last_name'], 'verbose_name': 'solicitud', 'verbose_name_plural': 'solicitudes'},
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='nombre',
        ),
        migrations.AddField(
            model_name='comuna',
            name='comuna',
            field=models.CharField(default=1, max_length=100, verbose_name='COMUNA'),
            preserve_default=False,
        ),
    ]
