# Generated by Django 5.0.4 on 2024-06-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_solicitud_options_remove_comuna_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('SE', 'Sin especificar')], default=1, max_length=2, verbose_name='GÉNERO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='TELÉFONO'),
        ),
    ]
