# Generated by Django 5.0.4 on 2024-06-05 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_solicitud_gender_alter_solicitud_phone_number'),
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='crud.product', verbose_name='PRODUCTO'),
            preserve_default=False,
        ),
    ]
