# Generated by Django 5.0.4 on 2024-06-13 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solicitud_product'),
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='product',
        ),
        migrations.CreateModel(
            name='SolicitudProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitud')),
            ],
            options={
                'verbose_name': 'Solicitud Producto',
                'verbose_name_plural': 'Solicitudes Productos',
            },
        ),
    ]
