# Generated by Django 5.0.4 on 2024-06-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_solicitud_product_solicitudproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudproducto',
            options={'verbose_name': 'solicitud producto', 'verbose_name_plural': 'solicitudes productos'},
        ),
    ]
