# Generated by Django 5.0.4 on 2024-06-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_solicitud_phone_number'),
        ('login', '0003_comuna_remove_user_solicitud_user_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='solicitudproducto',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='solicitudproducto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
