# Generated by Django 5.0.4 on 2024-07-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_solicitud_comuna_and_more'),
        ('crud', '0002_product_category_product_price_alter_product_cameras_and_more'),
        ('login', '0005_user_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('status', models.CharField(choices=[('PC', 'Pendiente Confirmación'), ('CF', 'Confirmado'), ('EP', 'En preparación'), ('EN', 'Entregado'), ('CN', 'Cancelado')], default='PC', max_length=2, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Precio unitario')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'detalle solicitud',
                'verbose_name_plural': 'detalle solicitudes',
            },
        ),
        migrations.DeleteModel(
            name='SolicitudProducto',
        ),
    ]
