# Generated by Django 5.0.4 on 2024-08-05 20:49

import django.db.models.deletion
import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=100, verbose_name='COMUNA')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='NOMBRE')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='APELLIDO')),
                ('birthday', models.DateField(default=login.models.default_birthday, null=True, verbose_name='FECHA DE NACIMIENTO')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='TELÉFONO')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('SE', 'Sin especificar')], default='SE', max_length=2, null=True, verbose_name='GÉNERO')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True, verbose_name='CORREO')),
                ('password', models.CharField(blank=True, max_length=250, null=True, verbose_name='CLAVE')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('rol', models.CharField(default='USER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.comuna', verbose_name='COMUNA')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
