# Generated by Django 5.0.4 on 2024-06-26 17:21

import django.db.models.deletion
import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_options_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=100, verbose_name='COMUNA')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=login.models.default_birthday, verbose_name='FECHA DE NACIMIENTO'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('SE', 'Sin especificar')], default='SE', max_length=2, verbose_name='GÉNERO'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Apellido por defecto', max_length=50, verbose_name='APELLIDO'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Nombre por defecto', max_length=50, verbose_name='NOMBRE'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='Teléfono por defecto', max_length=15, verbose_name='TELÉFONO'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250, null=True, verbose_name='Clave'),
        ),
        migrations.AddField(
            model_name='user',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.comuna', verbose_name='COMUNA'),
            preserve_default=False,
        ),
    ]
