# Generated by Django 5.0.4 on 2024-08-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='Producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('CA', 'Cámaras'), ('KI', 'Kits'), ('AC', 'Accesorios')], default='KI', max_length=2, verbose_name='Categoría')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Precio')),
                ('cameras', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cámaras')),
                ('channels', models.PositiveIntegerField(blank=True, null=True, verbose_name='Canales')),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['product'],
            },
        ),
    ]
