# Generated by Django 5.0.4 on 2024-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_product_category_product_price_alter_product_cameras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cameras',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cámaras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='channels',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Canales'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Precio'),
        ),
    ]
